import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Aeonik font
const Aeonik = localFont({
  src: "../fonts/Aeonik/AeonikPro-Regular.ttf",
});

export const metadata: Metadata = {
  title: "twistVisu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Aeonik.className}>{children}</body>
    </html>
  );
}
